sudo: required

language: node_js

services:
#  - docker
  - mysql

node_js:
  - "6.10.2"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8

before_install:
  - mysql -u root < ./shabbtech-schema.sql
  - mysqladmin -u root password 'root-secret-pw'
