version: "3"

volumes:
  app_data:
  sql_data:
  mongo_data:

services:


  app:
    image: shabbtech/app
    build: .
    volumes:
      - "app_data:/usr/shared/app"
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      - mongo


  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql-schema.sql:/docker-entrypoint-initdb.d/mysql-schema.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-secret-pw
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"


  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/usr/share/mongo
    ports:
      - "27017:27017"


  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../angular2/dist/:/usr/share/nginx/html
    ports:
     - 8080:80
    depends_on:
      - app


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
    ports:
      - 9200:9200
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'elastic:changeme', 'http://elasticsearch:9200']
